//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Post
    {
        public int Ad_id { get; set; }
        public string Ad_name { get; set; }
        public string Ad_image { get; set; }
        public string Ad_des { get; set; }
        public Nullable<int> pro_fk_Event_Category { get; set; }
        public Nullable<int> pro_fk_Alumni { get; set; }
    
        public virtual tbl_Event_Category tbl_Event_Category { get; set; }
        public virtual tbl_Alumni tbl_Alumni { get; set; }
    }
}
