//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Complain
    {
        public int ComplainID { get; set; }
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$", ErrorMessage = "Please enter a valid Name")]
        [Required(ErrorMessage = "Please enter  Name.")]
        public string Name { get; set; }
             [Required(ErrorMessage = "Please enter Description.")]
        public string Discription { get; set; }
         [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
         [Required(ErrorMessage = "Please enter  Email.")]
        public string Emain { get; set; }
        public Nullable<int> pro_fk_Student { get; set; }
        public Nullable<int> pro_fk_Alumni { get; set; }
        public string com { get; set; }
    
        public virtual student student { get; set; }
        public virtual tbl_Alumni tbl_Alumni { get; set; }
    }
}
