//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV
    {
        public int Cid { get; set; }
        public string fullname { get; set; }
        public string Email { get; set; }
        public string cv1 { get; set; }
        public Nullable<int> pro_fk_Student { get; set; }
        public Nullable<int> pro_fk_Alumni { get; set; }
    
        public virtual tbl_Alumni tbl_Alumni { get; set; }
        public virtual student student { get; set; }
    }
}
