//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Alumni_PortalEntities : DbContext
    {
        public Alumni_PortalEntities()
            : base("name=Alumni_PortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad_Post> Ad_Post { get; set; }
        public virtual DbSet<Complain> Complains { get; set; }
        public virtual DbSet<CV> CVs { get; set; }
        public virtual DbSet<going> goings { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Alumni> tbl_Alumni { get; set; }
        public virtual DbSet<tbl_Event_Category> tbl_Event_Category { get; set; }
    }
}
