//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alumni
    {
        public tbl_Alumni()
        {
            this.Ad_Post = new HashSet<Ad_Post>();
            this.Complains = new HashSet<Complain>();
            this.CVs = new HashSet<CV>();
            this.goings = new HashSet<going>();
        }
    
        public int Alumni_id { get; set; }
        public string Alumni_fullname { get; set; }
        public string Alumni_Enrolmentnum { get; set; }
        public string Alumni_email { get; set; }
        public string Alumni_cellnum { get; set; }
        public string Alumni_department { get; set; }
        public string Alumni_cmsid { get; set; }
    
        public virtual ICollection<Ad_Post> Ad_Post { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<CV> CVs { get; set; }
        public virtual ICollection<going> goings { get; set; }
    }
}
