//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin
    {
        public tbl_Admin()
        {
            this.tbl_Event_Category = new HashSet<tbl_Event_Category>();
        }
    
        public int admin_id { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
    
        public virtual ICollection<tbl_Event_Category> tbl_Event_Category { get; set; }
    }
}
