//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_Alumni
    {
        public tbl_Alumni()
        {
            this.Ad_Post = new HashSet<Ad_Post>();
            this.Complains = new HashSet<Complain>();
            this.CVs = new HashSet<CV>();
            this.goings = new HashSet<going>();
        }
    
        public int Alumni_id { get; set; }
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$",ErrorMessage = "Please enter a valid Name" )]
        [Required(ErrorMessage = "Please enter Full Name name.")]
        public string Alumni_fullname { get; set; }
           [Required(ErrorMessage = "Please enter Enrollment Number Number name.")]
        public string Alumni_Enrolmentnum { get; set; }
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
       
        public string Alumni_email { get; set; }
        [Required(ErrorMessage = "Please enter Cell Number name.")]
        public string Alumni_cellnum { get; set; }
        [Required(ErrorMessage = "Please enter department name.")]
        public string Alumni_department { get; set; }
        [Required(ErrorMessage = "Please enter CMS ID.")]
        public string Alumni_cmsid { get; set; }
    
        public virtual ICollection<Ad_Post> Ad_Post { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual ICollection<CV> CVs { get; set; }
        public virtual ICollection<going> goings { get; set; }
    }
}
