//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alumni_Student_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Event_Category
    {
        public tbl_Event_Category()
        {
            this.Ad_Post = new HashSet<Ad_Post>();
        }
    
        public int cat_id { get; set; }
        public string cat_Name { get; set; }
        public string cat_image { get; set; }
        public Nullable<int> cat_fk_admin { get; set; }
        public Nullable<int> cat_status { get; set; }
    
        public virtual ICollection<Ad_Post> Ad_Post { get; set; }
        public virtual tbl_Admin tbl_Admin { get; set; }
    }
}
